### ISSUE TITLE
Unify the notice about not exist the proper models and labels.

### ISSUE THREAD

**Issue by mojunsang26** [nnsuite/nnstreamer-example#60]
After building nnstreamer-example, I tried to execute the executables in "builddir/native/" without proper models and labels.

The executables about object_detection(nnstreamer_example_object_detection_*) returned the following error message:
```
$ ./nnstreamer_example_object_detection_tf
** (process:6390): CRITICAL **: 19:46:41.502: the file of model_path is not valid: ./tf_model/ssdlite_mobilenet_v2.pb
$ ./nnstreamer_example_object_detection_tflite
** (process:6444): CRITICAL **: 19:48:37.962: the file of model_path is not valid: ./tflite_model/ssd_mobilenet_v2_coco.tflite
```

However, Nothing happened when I executed the executables about image_classification(nnstreamer_example_image_classification_*). Because these make a message only in debugging mode.

In my opinion, It would be better that the examples even make an error message when it is not in debugging mode.

**Comment by myungjoo** [comment]
There are two ways to fix this:
1. Update image-classification example code to check the model path and emit errors if it cannot.
2. Update nnstreamer's tensor_filter so that it emits a proper and readable error messages.

Method 2 has higher impact and utility. Method 1 will be easier to implement, but has less impact and less reusability. I recommend to proceed with Method 2.
